### ISSUE TITLE
Main website master task

### ISSUE THREAD

**Issue by Jaedotmoe** [Jaedotmoe/meta#12]
This is the master task of `go-jae.fi` related enhancements.

Features:
- [ ] Database system for dynamic endpoints (https://github.com/Jaedotmoe/go-jae.fi/issues/2)
- [ ] Serve content from different repo to avoid rebuild on page change (https://github.com/Jaedotmoe/go-jae.fi/issues/8)
- [ ] Change markdown processor (https://github.com/Jaedotmoe/go-jae.fi/issues/9)

Bugs:
- [ ] Invalid content-length in console (https://github.com/Jaedotmoe/go-jae.fi/issues/10)
- [ ] Cannot create nested pages (https://github.com/Jaedotmoe/go-jae.fi/issues/11)
